name: Linter

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Remove unused imports with autoflake
        run: |
          pip install autoflake
          autoflake --in-place --remove-all-unused-imports --remove-unused-variables --recursive .

      - name: Sort imports with isort
        run: |
          pip install isort
          isort .

      - uses: astral-sh/ruff-action@v3
        with:
          args: "--version"
      - run: ruff check --fix
      - run: ruff format

      - name: Commit changes
        uses: EndBug/add-and-commit@v4
        with:
          author_name: ${{ github.actor }}
          author_email: ${{ github.actor }}@users.noreply.github.com
          message: "Format code"
          add: "."
          branch: ${{ github.ref }}
